### ISSUE TITLE
nad does not handle Python scripts in config dir on Windows

### ISSUE THREAD

**Issue by jsanghi** [circonus-labs/nad#29]
Wrote a custom stand-alone python script using twill to do synthetic login testing of a web application.  This works successfully when run manually or with python script.py via CLI.  I print out standard tab-separated data to stdout.  When nad calls the script in the config directory, I get the following error, and nad dies.

child_process.js:1155
    throw errnoException(err, 'spawn');
          ^
Error: spawn UNKNOWN
    at exports._errnoException (util.js:746:11)
    at ChildProcess.spawn (child_process.js:1155:11
    at exports.spawn (child_process.js:988:9)
    at run_script (E:\webmd\nad-master\nad:587:13)
    at E:\webmd\nad-master\nad:532:7
    at FSReqWrap.cb [as oncomplete] (fs.js:228:19)

Is there a custom module needed to run a python script, or will there be support for py scripts in the future?

**Comment by neophenix** [comment]
nad doesn't need any support for external script as it just spawns an external process to run them like anything else on the box, so it doesn't matter what they are written in.

I would verify that any environment params, etc are being passed correct when the script is run via nad and not from your user.

**Comment by jsanghi** [comment]
Thank you!  I was able to get the script running.  Can you advise on how to view the custom tab separated data in Circonus UI?

After verifying my data appears with a curl to localhost:2609  (login_fail\tL\t0), I created a check using Windows Node Agent Service.  While I am able to see all the Windows-specific metrics using 2609/wmi, I cannot remove the /wmi in advanced settings to get the base custom data that I am sending.  The /wmi auto-repopulates.

Thanks, I will close out issue.

**Comment by neophenix** [comment]
Try the normal node agent check instead of the "special" windows version.

**Comment by jsanghi** [comment]
Worked!  Cheers!
