### ISSUE TITLE
readlink -e does not work on FreeBSD

### ISSUE THREAD

**Issue by keithf4** [circonus-labs/nad#87]
Installed the latest nad on my FreeBSD system and all the postgres functions broke. Seems that the `-e` option does not exist for readlink on FreeBSD. 
```
$ sudo -u nobody ./pg_isready.sh
readlink: illegal option -- e
usage: readlink [-fn] [file ...]
usage: dirname string [...]
Unable to find pg functions /pg_functions.s
```
`-f` does exist on both linux and bsd and appears to give equivalent output, just doesn't do as much checking I guess?
```
  -f, --canonicalize            canonicalize by following every symlink in
                                every component of the given name recursively;
                                all but the last component must exist
  -e, --canonicalize-existing   canonicalize by following every symlink in
                                every component of the given name recursively,
                                all components must exist
```
```
$ readlink -f pg_isready.sh                                                                                 
/usr/local/etc/node-agent.d/postgresql/pg_isready.sh
```
Changed -e to -f and now it runs
```
$ sudo -u nobody ./pg_isready.sh
isready_status  l       0
```

I can do a push request to fix them all, but wanted to be sure this works as intended

**Comment by maier** [comment]
I believe it will if all the target platforms support the switch the same way. PR whenever you're ready.

**Comment by keithf4** [comment]
Pull request created https://github.com/circonus-labs/nad/pull/88
